# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-16 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
